---
title: "Mini Project 2"
author: "Entong Li, Zijia Cao, Jingyu Xie, Xindi Lu"
date: "10/31/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
load("CCES16_Common_OUTPUT_Feb2018_VV.RData")
library(gapminder)
library(dplyr)
library(tidyverse)
library(GGally)
cb_palette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
variables <- c("CC16_326", "CC16_410a", "commonweight_vv_post", "tookpost","gender","educ","race","pid7", "CC16_331_1","CC16_331_2","CC16_331_3","CC16_331_7")
```

# 1. Creating the data frame used in exploration:

```{r}
obama <- x[variables] %>%
  filter(CC16_326 == "Barack Obama", tookpost == "Yes")
obama$vote.T <- ifelse(obama$CC16_410a == "Donald Trump (Republican)", 1,0)

#For CC16_331_1 and CC16_331_3, "Yes" is a pro-immigration response.
for (i in c(9,11)){
  obama[i] <- ifelse(obama[i] == "Yes", 1 , 0)
}

#For CC16_331_2 and CC16_331_7, "No" is a pro-immigration response.
for (i in c(10,12)){
  obama[i] <- ifelse(obama[i] == "No", 1 , 0)
}

#Level of pro-immigration: 4 is the most, 0 is the lease.
obama$immig.at <- as.numeric(obama$CC16_331_1 + obama$CC16_331_2 + obama$CC16_331_3 + obama$CC16_331_7)

#Recode the race to four levels.
obama$race <- recode(obama$race,"White" = "White", "Black" = "Black", "Hispanic" = "Hispanic", .default = "Other")

#Recode the party identification to numeric variables:
#Strong to Lean Democrat: 3 to 1;
#Strong to Lean Republican: -3 to -1;
#Independent and others: 0
obama$pid7 <- recode_factor(obama$pid7, "Strong Democrat" = "Strong Democrat", "Not very strong Democrat" = "Not very strong Democrat", "Lean Democrat" = "Lean Democrat", "Strong Republican" = "Strong Republican", "Not very strong Republican" = "Not very strong Republican", "Lean Republican" = "Lean Republican", .default = "Other")

#Recode the education level to numeric variables:
#The higer value means higher education level, from 1-6.
#Skipped and Not Asked will be 0.
obama$educ <- recode(obama$educ, "No HS" = 1, "High school graduate" = 2, "Some college" = 3, "2-year" = 4, "4-year" = 5, "Post-grad" = 6, .default = 0)


#Recode the gender into three groups: Male, Female, Unknown(Skipped and Not asked)
obama$gender <- recode_factor(obama$gender, "Male" = "Male", "Female" = "Female", .default = "Unknown")
```


# 2.



```{r}
#obama.weighted.logit = glm(vote.T ~ immig.at, family = quasibinomial, weights = commonweight_vv_post, data = obama)

our.logit = function(x){
  coe = coef(obama.weighted.logit)
  y = coe[1] + coe[2] * x
  return(exp(y) / (1 + exp(y)))
}

#Immigration attitude with gender:
immig.gender.1 = glm(vote.T ~ immig.at + gender, family = quasibinomial, weights = commonweight_vv_post, data = obama)
immig.gender.2 = glm(vote.T ~ immig.at * gender, family = quasibinomial, weights = commonweight_vv_post, data = obama)
summary(immig.gender.1)
summary(immig.gender.2)
gender.df = expand.grid(immig.at = 0:4, gender = factor(c("Male","Female")))
gender.pred = predict(immig.gender.2, type = "response", newdata =gender.df )
gender.pred.df = data.frame(gender.df, vote.T.prob = as.vector(gender.pred))
ggplot(gender.pred.df, aes(x = immig.at, y = vote.T.prob, group = gender, color = gender)) + geom_line() + xlab("Immigration attitude") + ylab("Probability of voting Donald Trump")
ggplot(gender.pred.df, aes(x = gender, y = vote.T.prob, group = immig.at, color = immig.at)) + geom_line() + labs(color = "Immigration attitude") + ylab("Probability of voting Donald Trump")




#Immigration attitude with education level:
immig.educ.1 = glm(vote.T ~ immig.at + educ, family = quasibinomial, weights = commonweight_vv_post, data = obama)
immig.educ.2 = glm(vote.T ~ immig.at * educ, family = quasibinomial, weights = commonweight_vv_post, data = obama)
summary(immig.educ.1)
summary(immig.educ.2)
educ.df = expand.grid(immig.at = 0:4, educ = 1:6)
educ.pred = predict(immig.educ.2, type = "response", newdata =educ.df )
educ.pred.df = data.frame(educ.df, vote.T.prob = as.vector(educ.pred))
ggplot(educ.pred.df, aes(x = immig.at, y = vote.T.prob, group = educ, color = educ)) + geom_line() + xlab("Immigration attitude") + ylab("Probability of voting Donald Trump") + labs(color = "education level")
ggplot(educ.pred.df, aes(x = educ, y = vote.T.prob, group = immig.at, color = immig.at)) + geom_line() + labs(color = "Immigration attitude") + ylab("Probability of voting Donald Trump")


#Immigration attitude with race:
immig.race.1 = glm(vote.T ~ immig.at + race, family = quasibinomial, weights = commonweight_vv_post, data = obama)
immig.race.2 = glm(vote.T ~ immig.at * race , family = quasibinomial, weights = commonweight_vv_post, data = obama)
summary(immig.race.1)
summary(immig.race.2)
race.df = expand.grid(immig.at = 0:4, race = factor(c("White","Black","Hispanic","Other")))
race.pred = predict(immig.race.2, type = "response", newdata =race.df )
race.pred.df = data.frame(race.df, vote.T.prob = as.vector(race.pred))
ggplot(race.pred.df, aes(x = immig.at, y = vote.T.prob, group = race, color = race)) + geom_line() + xlab("Immigration attitude") + ylab("Probability of voting Donald Trump") 
ggplot(race.pred.df, aes(x = race, y = vote.T.prob, group = immig.at, color = immig.at)) + geom_line() + labs(color = "Immigration attitude") + ylab("Probability of voting Donald Trump")

#Immigration attitude with party:
immig.party.1 = glm(vote.T ~ immig.at + pid7, family = quasibinomial, weights = commonweight_vv_post, data = obama)
immig.party.2 = glm(vote.T ~ immig.at * pid7 , family = quasibinomial, weights = commonweight_vv_post, data = obama)
summary(immig.party.1)
summary(immig.party.2)
party.df = expand.grid(immig.at = 0:4, pid7 = factor(c("Strong Democrat", "Not very strong Democrat", "Lean Democrat", "Strong Republican",  "Not very strong Republican", "Lean Republican",  "Other")))
party.pred = predict(immig.party.2, type = "response", newdata =party.df )
party.pred.df = data.frame(party.df, vote.T.prob = as.vector(party.pred))
ggplot(party.pred.df, aes(x = immig.at, y = vote.T.prob, group = pid7, color = pid7)) + geom_line() + xlab("Immigration attitude") + ylab("Probability of voting Donald Trump") + labs(color = "Party")
ggplot(party.pred.df, aes(x = pid7, y = vote.T.prob, group = immig.at, color = immig.at)) + geom_line() + labs(color = "Immigration attitude") + ylab("Probability of voting Donald Trump")

```
